name: "Bug Report"
description: "Report a reproducible bug in UltraPreciseKeyMaster"
title: "[Bug] <describe-the-problem>"
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out this form completely so we can help fix it quickly.

  - type: textarea
    id: bug-summary
    attributes:
      label: "Brief Summary"
      placeholder: "e.g., Key not releasing after hold"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Describe what you did to trigger the bug."
      placeholder: |
        1. Start the script
        2. Hold `E`
        3. Notice that the key doesn't release
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "What should have happened?"
      placeholder: "The key should release after the set hold time."
    validations:
      required: true

  - type: dropdown
    id: ahk-version
    attributes:
      label: "AutoHotkey Version"
      options:
        - "AutoHotkey v2"
        - "AutoHotkey v1.1"
        - "I'm not sure"
        - "Other (please specify below)"
    validations:
      required: true

  - type: input
    id: ahk-version-other
    attributes:
      label: "If 'Other', specify the AHK version"
      placeholder: "e.g., AutoHotkey_H v2.1-beta"

  - type: dropdown
    id: platform
    attributes:
      label: "Operating System"
      options:
        - "Windows 11"
        - "Windows 10"
        - "Windows 8.1 or older"
        - "Other (please specify below)"
    validations:
      required: true

  - type: input
    id: platform-other
    attributes:
      label: "If 'Other', specify your OS"
      placeholder: "e.g., Windows Server 2022"

  - type: textarea
    id: logs
    attributes:
      label: "Additional Notes / Logs"
      description: "Any error messages, screenshots, or observations?"
      placeholder: "Paste logs, screenshots, or relevant comments here."
